# Linux服务器部署配置模板
# 这个文件包含基本的配置结构，敏感信息建议通过环境变量设置

# CODING平台配置
coding:
  # 这些配置可以通过环境变量覆盖：
  # CODING_TOKEN, CODING_TEAM_ID
  token: "your_coding_token_here"  # 或使用环境变量 CODING_TOKEN
  team_id: 12345                   # 或使用环境变量 CODING_TEAM_ID

  # Maven仓库认证配置（如果CODING仓库需要认证）
  maven_repositories:
    snapshots:
      username: ""
      password: ""
    releases:
      username: ""
      password: ""

  # 包过滤配置
  maven_filter:
    enabled: true
    patterns: ["com.yourcompany.*"]  # 根据实际情况修改

  # 分页配置
  pagination:
    page_size: 50     # 每页数量，可根据服务器性能调整
    max_pages: 100    # 最大页数限制

  # 性能配置（针对Linux服务器优化）
  performance:
    max_workers: 2    # 并发工作线程数，建议CPU核心数的1-2倍
    batch_size: 20    # 批处理大小，减少内存占用

# Nexus仓库配置
nexus:
  # 这些配置可以通过环境变量覆盖：
  # NEXUS_URL, NEXUS_USERNAME, NEXUS_PASSWORD
  # NEXUS_REPOSITORY, NEXUS_SNAPSHOT_REPOSITORY
  url: "http://your-nexus-server:8081"        # 或使用环境变量 NEXUS_URL
  username: "your_nexus_username"            # 或使用环境变量 NEXUS_USERNAME
  password: "your_nexus_password"            # 或使用环境变量 NEXUS_PASSWORD

  # 仓库名称配置
  repository: "maven-releases"              # 或使用环境变量 NEXUS_REPOSITORY
  snapshot_repo: "maven-snapshots"          # 或使用环境变量 NEXUS_SNAPSHOT_REPOSITORY
  release_repo: "maven-releases"             # 或使用环境变量 NEXUS_REPOSITORY

# 迁移配置
migration:
  # 要迁移的项目列表，留空表示迁移所有项目
  project_names: []  # 例如: ["project1", "project2"]

  # 下载配置
  download_path: "./downloads"  # 临时下载目录

  # 并发配置
  batch_size: 20           # 批处理大小
  parallel_downloads: 2   # 并行下载数量

# 内存优化配置（适用于低内存服务器）
memory_optimization:
  # 内存限制（MB）
  max_memory_mb: 512

  # 队列大小
  queue_size: 20

  # 清理间隔（秒）
  cleanup_interval: 60

# 日志配置
logging:
  level: "INFO"           # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "migration.log"   # 日志文件名，空则输出到控制台
  max_size_mb: 10        # 日志文件最大大小（MB）
  backup_count: 5        # 保留的日志文件数量

# 重试配置
retry:
  max_attempts: 3        # 最大重试次数
  delay_seconds: 5       # 重试延迟（秒）
  backoff_factor: 2      # 退避因子

# 速率限制配置（避免触发API限制）
rate_limit:
  requests_per_second: 5  # 每秒请求数
  burst_size: 10          # 突发请求大小