"""
内存流流水线迁移器 - 零磁盘占用的边下载边上传迁移
"""

import os
import json
import hashlib
import logging
import threading
import tempfile
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple, Set
from concurrent.futures import ThreadPoolExecutor, as_completed
from queue import Queue, Empty
from dataclasses import dataclass, field
from tqdm import tqdm
import time
import io

from .models import MavenArtifact, MigrationConfig
from .coding_client import CodingClient
from .nexus_uploader import NexusUploader


logger = logging.getLogger(__name__)


@dataclass
class MemoryMigrationTask:
    """内存迁移任务"""
    artifact: MavenArtifact
    file_hash: Optional[str] = None
    download_success: bool = False
    upload_success: bool = False
    error_message: Optional[str] = None
    file_data: Optional[bytes] = None
    created_time: float = field(default_factory=time.time)  # 任务创建时间


class MemoryPipelineMigrator:
    """内存流流水线迁移器 - 零磁盘占用"""

    def __init__(self, config: MigrationConfig):
        """
        初始化内存流水线迁移器

        Args:
            config: 迁移配置
        """
        self.config = config
        self.coding_client = CodingClient(
            config.coding_token,
            config.coding_team_id,
            config.maven_repositories,
            config.pagination,
            config.performance.max_workers,
            requests_per_second=config.rate_limit.requests_per_second
        )
        self.nexus_uploader = NexusUploader(config)

        # 性能配置
        self.download_workers = config.performance.max_workers
        self.upload_workers = min(config.performance.max_workers // 2, 5)

        # 任务队列
        self.upload_queue = Queue(maxsize=50)  # 减小队列大小，减少内存占用
        self.completed_tasks = []
        self.failed_tasks = []

        # 统计信息
        self.stats = {
            'total_artifacts': 0,
            'downloaded': 0,
            'uploaded': 0,
            'download_failed': 0,
            'upload_failed': 0,
            'skipped_existing': 0
        }

        # 控制标志
        self.stop_event = threading.Event()

        # 迁移记录目录（固定目录，支持增量迁移）
        self.records_dir = Path("target")
        self.records_dir.mkdir(exist_ok=True)

        # 内存监控
        self.last_memory_check = time.time()
        self.memory_check_interval = 30  # 每30秒检查一次内存

        # 迁移记录文件和依赖列表（将在migrate_project中初始化）
        self.record_file = None
        self.uploaded_hashes: Set[str] = set()
        self.uploaded_dependencies = []

        # 内存限制（单位：字节）
        self.max_memory_usage = 100 * 1024 * 1024  # 100MB
        self.current_memory_usage = 0
        self.memory_lock = threading.Lock()

        # POM 文件追踪和调试
        self.pom_stats = {
            'discovered_in_coding': 0,      # 在CODING中发现的POM文件数
            'skipped_already_uploaded': 0,  # 跳过已上传的POM文件数
            'download_attempted': 0,        # 尝试下载的POM文件数
            'download_success': 0,          # 下载成功的POM文件数
            'download_failed': 0,           # 下载失败的POM文件数
            'upload_attempted': 0,          # 尝试上传的POM文件数
            'upload_success': 0,            # 上传成功的POM文件数
            'upload_failed': 0,             # 上传失败的POM文件数
            'missing_in_nexus': []          # 最终缺失的POM文件列表
        }
        self.pom_lock = threading.Lock()

        # 失败依赖路径日志记录
        self.failed_logs_lock = threading.Lock()
        self.failed_download_log = self.records_dir / "failed_downloads.log"
        self.failed_upload_log = self.records_dir / "failed_uploads.log"

        # 初始化失败日志文件
        self._init_failed_logs()

    def _init_failed_logs(self) -> None:
        """初始化失败日志文件"""
        try:
            # 创建下载失败日志文件
            if not self.failed_download_log.exists():
                with open(self.failed_download_log, 'w', encoding='utf-8') as f:
                    f.write("# CODING Maven 制品下载失败记录\n")
                    f.write("# 格式: 时间戳 | Maven坐标 | 文件路径 | 错误信息\n")
                    f.write("# Generated by Memory Pipeline Migrator\n\n")

            # 创建上传失败日志文件
            if not self.failed_upload_log.exists():
                with open(self.failed_upload_log, 'w', encoding='utf-8') as f:
                    f.write("# Nexus Maven 制品上传失败记录\n")
                    f.write("# 格式: 时间戳 | Maven坐标 | Maven路径 | 错误信息\n")
                    f.write("# Generated by Memory Pipeline Migrator\n\n")

            logger.debug(f"Failed logs initialized: {self.failed_download_log}, {self.failed_upload_log}")
        except Exception as e:
            logger.error(f"Failed to initialize failed logs: {e}")

    def _log_failed_download(self, artifact: MavenArtifact, error_message: str) -> None:
        """记录下载失败的依赖路径"""
        try:
            with self.failed_logs_lock:
                timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
                maven_coord = f"{artifact.group_id}:{artifact.artifact_id}:{artifact.version}:{artifact.packaging}"

                log_entry = f"{timestamp} | {maven_coord} | {artifact.file_path} | {error_message}\n"

                with open(self.failed_download_log, 'a', encoding='utf-8') as f:
                    f.write(log_entry)

                logger.debug(f"Logged failed download: {maven_coord}")
        except Exception as e:
            logger.error(f"Failed to log download failure: {e}")

    def _log_failed_upload(self, artifact: MavenArtifact, maven_path: str, error_message: str) -> None:
        """记录上传失败的依赖路径"""
        try:
            with self.failed_logs_lock:
                timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
                maven_coord = f"{artifact.group_id}:{artifact.artifact_id}:{artifact.version}:{artifact.packaging}"

                log_entry = f"{timestamp} | {maven_coord} | {maven_path} | {error_message}\n"

                with open(self.failed_upload_log, 'a', encoding='utf-8') as f:
                    f.write(log_entry)

                logger.debug(f"Logged failed upload: {maven_coord}")
        except Exception as e:
            logger.error(f"Failed to log upload failure: {e}")

    def _load_migration_records(self) -> None:
        """加载已迁移记录"""
        try:
            if self.record_file.exists():
                with open(self.record_file, 'r', encoding='utf-8') as f:
                    records = json.load(f)
                    self.uploaded_hashes = set(records.get('uploaded_hashes', []))
                    self.uploaded_dependencies = records.get('uploaded_dependencies', [])
                logger.info(f"Loaded {len(self.uploaded_hashes)} migration records")
                if self.uploaded_dependencies:
                    logger.info(f"Previously uploaded {len(self.uploaded_dependencies)} dependencies")
        except Exception as e:
            logger.warning(f"Failed to load migration records: {e}")
            self.uploaded_hashes = set()
            self.uploaded_dependencies = []

    def _save_migration_records(self) -> None:
        """保存迁移记录"""
        try:
            records = {
                'uploaded_hashes': list(self.uploaded_hashes),
                'uploaded_dependencies': self.uploaded_dependencies,
                'last_updated': time.time()
            }
            with open(self.record_file, 'w', encoding='utf-8') as f:
                json.dump(records, f, indent=2, ensure_ascii=False)
            logger.debug(f"Saved {len(self.uploaded_hashes)} migration records")
        except Exception as e:
            logger.error(f"Failed to save migration records: {e}")

    def _calculate_file_hash(self, file_data: bytes) -> str:
        """计算文件哈希值"""
        return hashlib.sha256(file_data).hexdigest()

    def _check_if_already_uploaded(self, artifact: MavenArtifact) -> Optional[str]:
        """检查文件是否已经上传过"""
        # 生成唯一标识
        identifier = f"{artifact.group_id}:{artifact.artifact_id}:{artifact.version}:{artifact.packaging}"
        hash_identifier = hashlib.md5(identifier.encode()).hexdigest()

        if hash_identifier in self.uploaded_hashes:
            return hash_identifier
        return None

    def migrate_project(self, project_id: int, project_name: str) -> Dict[str, Any]:
        """
        迁移单个项目（内存流模式）

        Args:
            project_id: 项目 ID
            project_name: 项目名称

        Returns:
            迁移结果统计
        """
        logger.info(f"Starting memory pipeline migration for project: {project_name}")

        try:
            # 初始化迁移记录文件（按项目和项目ID区分）
            self.record_file = self.records_dir / f"migration_records_{project_name}_{project_id}.json"
            self._load_migration_records()

            # 获取所有制品
            all_artifacts = self._get_all_artifacts(project_id)
            self.stats['total_artifacts'] = len(all_artifacts)

            if not all_artifacts:
                logger.warning(f"No artifacts found for project: {project_name}")
                return self.stats

            # 过滤已上传的制品
            filtered_artifacts = []
            for artifact in all_artifacts:
                existing_hash = self._check_if_already_uploaded(artifact)
                if existing_hash:
                    self.stats['skipped_existing'] += 1
                    logger.debug(f"Skipping already uploaded: {artifact.file_path}")
                else:
                    filtered_artifacts.append(artifact)

            logger.info(f"Found {len(all_artifacts)} total artifacts, {len(filtered_artifacts)} to migrate "
                       f"({self.stats['skipped_existing']} already uploaded)")

            if not filtered_artifacts:
                logger.info("All artifacts have already been migrated")
                return self.stats

            # 启动下载和上传线程池
            with ThreadPoolExecutor(max_workers=self.download_workers + self.upload_workers) as executor:
                # 启动上传工作线程
                upload_futures = []
                for i in range(self.upload_workers):
                    future = executor.submit(self._upload_worker)
                    upload_futures.append(future)

                # 启动下载任务
                download_futures = []
                progress_bar = tqdm(total=len(filtered_artifacts), desc="Memory Pipeline",
                                  unit="files", postfix={"down": 0, "up": 0, "skip": self.stats['skipped_existing']})

                for artifact in filtered_artifacts:
                    future = executor.submit(self._download_and_queue, artifact, progress_bar)
                    download_futures.append(future)

                # 等待所有下载任务完成
                for future in as_completed(download_futures):
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Download task failed: {e}")

                # 等待上传队列清空
                logger.info("Waiting for upload queue to empty...")
                queue_wait_count = 0
                max_queue_wait = 600  # 最大等待60秒
                while not self.upload_queue.empty() and queue_wait_count < max_queue_wait:
                    queue_wait_count += 1
                    if queue_wait_count % 50 == 0:  # 每5秒打印一次
                        logger.info(f"Upload queue size: {self.upload_queue.qsize()}, waiting... ({queue_wait_count * 0.1:.1f}s)")
                    time.sleep(0.1)

                if not self.upload_queue.empty():
                    logger.warning(f"Upload queue not empty after timeout, {self.upload_queue.qsize()} items remaining")

                # 停止上传工作线程
                self.stop_event.set()

                # 等待上传线程完成
                for future in upload_futures:
                    future.result()

                progress_bar.close()

        except Exception as e:
            logger.error(f"Memory pipeline migration failed: {e}")
        finally:
            # 保存迁移记录
            self._save_migration_records()

        # 生成最终统计
        self._generate_final_stats()

        # 显示已上传的依赖汇总
        self._display_uploaded_dependencies_summary()

        # 显示POM文件详细统计报告
        self._display_pom_detailed_report()

        return self.stats

    def _generate_final_stats(self) -> None:
        """生成最终统计信息"""
        logger.info("=" * 60)
        logger.info("MEMORY PIPELINE MIGRATION SUMMARY")
        logger.info("=" * 60)
        logger.info(f"[OK] Total artifacts processed: {self.stats['total_artifacts']}")
        logger.info(f"⬇️  Downloaded: {self.stats['downloaded']}")
        logger.info(f"⬆️  Uploaded: {self.stats['uploaded']}")
        logger.info(f"⏭️  Skipped (already uploaded): {self.stats['skipped_existing']}")
        logger.info(f"[ERROR] Download failed: {self.stats['download_failed']}")
        logger.info(f"[ERROR] Upload failed: {self.stats['upload_failed']}")
        logger.info("=" * 60)

    def _display_uploaded_dependencies_summary(self) -> None:
        """显示已上传依赖的汇总信息"""
        if not self.uploaded_dependencies:
            logger.info("[INFO] No new dependencies uploaded in this session")
            return

        logger.info("")
        logger.info("[INFO] UPLOADED DEPENDENCIES SUMMARY")
        logger.info("=" * 60)

        # 按group_id和artifact_id分组显示
        grouped_deps = {}
        for dep in self.uploaded_dependencies:
            key = f"{dep['group_id']}:{dep['artifact_id']}"
            if key not in grouped_deps:
                grouped_deps[key] = []
            grouped_deps[key].append(dep)

        for group_key, deps in sorted(grouped_deps.items()):
            logger.info(f"📋 {group_key}")
            for dep in sorted(deps, key=lambda x: x['version']):
                logger.info(f"   🏷️  {dep['version']} ({dep['packaging']}) - {dep['repository']}")

        logger.info("=" * 60)
        logger.info(f"📈 Total dependencies uploaded: {len(self.uploaded_dependencies)}")
        logger.info("")

    def _get_all_artifacts(self, project_id: int) -> List[MavenArtifact]:
        """获取所有制品"""
        all_artifacts = []

        # 获取项目名称
        project_name = self.coding_client.get_project_name_by_id(project_id)

        # 获取制品仓库
        repositories = self.coding_client.get_artifact_repositories(project_id)
        maven_repos = [repo for repo in repositories if repo.get('Type') == 3]

        for repo in maven_repos:
            repo_name = repo.get('Name', '')
            logger.info(f"Processing repository: {repo_name}")

            try:
                artifacts = self.coding_client.get_maven_artifacts(
                    project_id, repo_name, self.config.maven_filter
                )
                all_artifacts.extend(artifacts)
                logger.info(f"Found {len(artifacts)} artifacts in repository: {repo_name}")

                # 统计POM文件
                pom_artifacts = [art for art in artifacts if art.file_path.endswith('.pom')]
                with self.pom_lock:
                    self.pom_stats['discovered_in_coding'] += len(pom_artifacts)

                if pom_artifacts:
                    logger.info(f"[POM DEBUG] Found {len(pom_artifacts)} POM files in repository {repo_name}")
                    # 记录前几个POM文件用于调试
                    for i, pom in enumerate(pom_artifacts[:3]):
                        logger.info(f"[POM DEBUG]   POM {i+1}: {pom.group_id}:{pom.artifact_id}:{pom.version} ({pom.file_path})")
                    if len(pom_artifacts) > 3:
                        logger.info(f"[POM DEBUG]   ... and {len(pom_artifacts) - 3} more POM files")

            except Exception as e:
                logger.error(f"Failed to get artifacts from repository {repo_name}: {e}")

        return all_artifacts

    def _download_and_queue(self, artifact: MavenArtifact, progress_bar: tqdm) -> bool:
        """
        下载制品到内存并加入上传队列

        Args:
            artifact: 制品信息
            progress_bar: 进度条

        Returns:
            下载是否成功
        """
        if self.stop_event.is_set():
            return False

        # 检查是否已经上传过
        existing_hash = self._check_if_already_uploaded(artifact)
        if existing_hash:
            # POM文件特殊处理
            if artifact.file_path.endswith('.pom') or artifact.packaging == 'pom':
                with self.pom_lock:
                    self.pom_stats['skipped_already_uploaded'] += 1
                logger.info(f"[POM DEBUG] ⏭️  SKIP POM: {artifact.group_id}:{artifact.artifact_id}:{artifact.version} already uploaded")
            else:
                logger.info(f"⏭️  SKIP: {artifact.group_id}:{artifact.artifact_id}:{artifact.version} already uploaded")
            self.stats['skipped_existing'] += 1
            progress_bar.set_postfix({"down": self.stats['downloaded'],
                                       "up": self.stats['uploaded'],
                                       "skip": self.stats['skipped_existing']})
            return True

        task = MemoryMigrationTask(artifact=artifact)

        try:
            # POM文件下载统计
            is_pom_file = artifact.file_path.endswith('.pom') or artifact.packaging == 'pom'
            if is_pom_file:
                with self.pom_lock:
                    self.pom_stats['download_attempted'] += 1
                logger.info(f"[POM DEBUG] 🔄 STARTING POM DOWNLOAD: {artifact.group_id}:{artifact.artifact_id}:{artifact.version}")
                logger.info(f"[POM DEBUG]   File path: {artifact.file_path}")
                logger.info(f"[POM DEBUG]   Repository: {artifact.repository}")
                if hasattr(artifact, 'download_url') and artifact.download_url:
                    logger.info(f"[POM DEBUG]   Download URL: {artifact.download_url}")

            # 定期内存检查和清理
            current_time = time.time()
            if current_time - self.last_memory_check > self.memory_check_interval:
                self._check_and_cleanup_memory()
                self.last_memory_check = current_time

            # 检查内存使用限制
            with self.memory_lock:
                if self.current_memory_usage > self.max_memory_usage:
                    logger.warning(f"Memory usage limit reached: {self.current_memory_usage}/{self.max_memory_usage} bytes, waiting...")
                    wait_count = 0
                    max_wait_time = 300  # 最大等待30秒
                    while self.current_memory_usage > self.max_memory_usage * 0.5:
                        wait_count += 1
                        if wait_count % 10 == 0:  # 每1秒打印一次
                            logger.info(f"Waiting for memory release: {self.current_memory_usage}/{self.max_memory_usage} bytes (waited {wait_count * 0.1:.1f}s)")
                        if wait_count >= max_wait_time:  # 超时保护
                            logger.error(f"Memory wait timeout after {max_wait_time * 0.1:.1f}s, forcing continue")
                            # 强制清理一些内存：清理失败的任务
                            self._emergency_memory_cleanup()
                            break
                        time.sleep(0.1)

            # 下载文件到内存
            file_data = self._download_to_memory(artifact)

            if file_data:
                task.file_data = file_data
                task.file_hash = self._calculate_file_hash(file_data)
                task.download_success = True
                self.stats['downloaded'] += 1

                # POM文件下载成功统计
                if is_pom_file:
                    with self.pom_lock:
                        self.pom_stats['download_success'] += 1
                    logger.info(f"[POM DEBUG] ✅ POM DOWNLOAD SUCCESS: {artifact.group_id}:{artifact.artifact_id}:{artifact.version}")
                    logger.info(f"[POM DEBUG]   File size: {len(file_data)} bytes")
                    logger.info(f"[POM DEBUG]   File hash: {task.file_hash[:16]}...")

                # 更新内存使用量
                with self.memory_lock:
                    self.current_memory_usage += len(file_data)

                # 加入上传队列
                try:
                    self.upload_queue.put(task, timeout=30)
                except Exception as queue_error:
                    logger.error(f"Failed to add task to upload queue: {queue_error}")
                    task.error_message = f"Queue error: {queue_error}"
                    self.stats['upload_failed'] += 1
                    self.failed_tasks.append(task)

                    # 记录上传失败到日志文件（队列错误也算上传失败）
                    maven_path = self._convert_to_maven_path(artifact)
                    self._log_failed_upload(artifact, maven_path, task.error_message)

                    # POM文件队列失败统计
                    if is_pom_file:
                        with self.pom_lock:
                            self.pom_stats['upload_failed'] += 1
                        logger.error(f"[POM DEBUG] ❌ POM QUEUE FAILED: {artifact.group_id}:{artifact.artifact_id}:{artifact.version} - {queue_error}")
                    # 释放内存
                    with self.memory_lock:
                        self.current_memory_usage -= len(file_data)
                    logger.debug(f"Released memory due to queue error: {len(file_data)} bytes, current usage: {self.current_memory_usage}")
                    task.file_data = None
                    return False

                logger.debug(f"Downloaded and queued: {artifact.file_path} ({len(file_data)} bytes)")

            else:
                task.error_message = "Download failed"
                self.stats['download_failed'] += 1
                self.failed_tasks.append(task)

                # 记录下载失败到日志文件
                self._log_failed_download(artifact, task.error_message)

                # POM文件下载失败统计
                if is_pom_file:
                    with self.pom_lock:
                        self.pom_stats['download_failed'] += 1
                    logger.error(f"[POM DEBUG] ❌ POM DOWNLOAD FAILED: {artifact.group_id}:{artifact.artifact_id}:{artifact.version} - {task.error_message}")

        except Exception as e:
            task.error_message = str(e)
            self.stats['download_failed'] += 1
            self.failed_tasks.append(task)

            # 记录下载失败到日志文件
            self._log_failed_download(artifact, task.error_message)

            logger.error(f"Failed to download {artifact.file_path}: {e}")

        # 确保在所有情况下都清理内存
        if hasattr(task, 'file_data') and task.file_data is not None:
            with self.memory_lock:
                self.current_memory_usage -= len(task.file_data)
            logger.debug(f"Cleaned up memory: {len(task.file_data)} bytes, current usage: {self.current_memory_usage}")
            task.file_data = None

        # 更新进度条
        progress_bar.set_postfix({"down": self.stats['downloaded'],
                                   "up": self.stats['uploaded'],
                                   "skip": self.stats['skipped_existing']})
        progress_bar.update(1)

        return task.download_success

    def _emergency_memory_cleanup(self) -> None:
        """紧急内存清理：清理失败的任务内存"""
        try:
            with self.memory_lock:
                # 清理失败的任务内存
                cleared_memory = 0
                for task in self.failed_tasks[:]:  # 复制列表，避免修改时出错
                    if hasattr(task, 'file_data') and task.file_data is not None:
                        file_size = len(task.file_data)
                        self.current_memory_usage -= file_size
                        cleared_memory += file_size
                        task.file_data = None

                # 清理上传队列中的任务内存
                temp_tasks = []
                while not self.upload_queue.empty():
                    try:
                        task = self.upload_queue.get_nowait()
                        if hasattr(task, 'file_data') and task.file_data is not None:
                            file_size = len(task.file_data)
                            self.current_memory_usage -= file_size
                            cleared_memory += file_size
                            task.file_data = None
                        temp_tasks.append(task)
                    except:
                        break

                # 将任务放回队列（没有内存数据的）
                for task in temp_tasks:
                    try:
                        self.upload_queue.put_nowait(task)
                    except:
                        pass

                if cleared_memory > 0:
                    logger.warning(f"Emergency cleanup: released {cleared_memory} bytes, current usage: {self.current_memory_usage}")

        except Exception as e:
            logger.error(f"Error during emergency memory cleanup: {e}")

    def _check_and_cleanup_memory(self) -> None:
        """定期检查和清理内存"""
        try:
            with self.memory_lock:
                memory_usage_mb = self.current_memory_usage / (1024 * 1024)
                limit_mb = self.max_memory_usage / (1024 * 1024)

                # 如果内存使用超过80%的阈值，进行预防性清理
                if memory_usage_mb > limit_mb * 0.8:
                    logger.info(f"Memory usage high ({memory_usage_mb:.1f}MB/{limit_mb:.1f}MB), performing preventive cleanup")
                    self._preventive_memory_cleanup()

                # 每5分钟记录一次内存统计
                if hasattr(self, '_last_stats_log'):
                    if time.time() - self._last_stats_log > 300:
                        logger.info(f"Memory statistics: {memory_usage_mb:.1f}MB/{limit_mb:.1f}MB, "
                                   f"Queue size: {self.upload_queue.qsize()}, "
                                   f"Failed tasks: {len(self.failed_tasks)}")
                        self._last_stats_log = time.time()
                else:
                    self._last_stats_log = time.time()

        except Exception as e:
            logger.error(f"Error during memory check: {e}")

    def _preventive_memory_cleanup(self) -> None:
        """预防性内存清理：清理旧的任务内存"""
        try:
            cleared_memory = 0

            # 清理上传队列中等待时间过长的任务（超过5分钟）
            current_time = time.time()
            temp_tasks = []
            while not self.upload_queue.empty():
                try:
                    task = self.upload_queue.get_nowait()
                    # 检查任务是否等待时间过长
                    if hasattr(task, 'file_data') and task.file_data is not None:
                        # 如果任务创建时间超过5分钟，清理内存但保留任务
                        if hasattr(task, 'created_time'):
                            if current_time - task.created_time > 300:  # 5分钟
                                file_size = len(task.file_data)
                                self.current_memory_usage -= file_size
                                cleared_memory += file_size
                                task.file_data = None
                                logger.debug(f"Preventive cleanup: released {file_size} bytes from old task")
                        else:
                            # 没有创建时间信息，也清理以防万一
                            file_size = len(task.file_data)
                            self.current_memory_usage -= file_size
                            cleared_memory += file_size
                            task.file_data = None
                            logger.debug(f"Preventive cleanup: released {file_size} bytes from unknown task")
                    temp_tasks.append(task)
                except:
                    break

            # 将任务放回队列
            for task in temp_tasks:
                try:
                    self.upload_queue.put_nowait(task)
                except:
                    pass

            if cleared_memory > 0:
                logger.info(f"Preventive cleanup: released {cleared_memory} bytes")

        except Exception as e:
            logger.error(f"Error during preventive memory cleanup: {e}")

    def _download_artifact_simple(self, artifact: MavenArtifact) -> bool:
        """
        简化的制品下载方法（用于组件迁移）

        Args:
            artifact: 制品信息

        Returns:
            下载是否成功
        """
        if self.stop_event.is_set():
            return False

        try:
            # 下载到内存
            file_data = self._download_to_memory(artifact)
            if not file_data:
                logger.error(f"Failed to download {artifact.file_path}")
                self.stats['download_failed'] += 1
                return False

            # 创建内存任务对象
            task = MemoryMigrationTask(
                artifact=artifact,
                file_data=file_data,
                download_success=True
            )

            # 添加到上传队列
            self.upload_queue.put(task)
            self.stats['downloaded'] += 1
            logger.debug(f"Successfully downloaded and queued: {artifact.file_path}")
            return True

        except Exception as e:
            logger.error(f"Download failed for {artifact.file_path}: {e}")
            self.stats['download_failed'] += 1
            self._log_failed_download(artifact, str(e))
            return False

    def _download_to_memory(self, artifact: MavenArtifact) -> Optional[bytes]:
        """下载文件到内存"""
        try:
            # 创建临时目录避免权限问题
            temp_dir = tempfile.mkdtemp()
            temp_file_path = os.path.join(temp_dir, f"temp_{hash(artifact.file_path)}.tmp")

            try:
                success = self.coding_client.download_artifact(
                    artifact.file_path.split('/')[0],  # project_name from file_path
                    "releases" if "releases" in artifact.file_path else "snapshots",
                    artifact.file_path,
                    temp_file_path,
                    getattr(artifact, 'download_url', None)
                )

                if success and os.path.exists(temp_file_path):
                    # 读取文件到内存
                    with open(temp_file_path, 'rb') as f:
                        file_data = f.read()
                    return file_data
                else:
                    return None

            finally:
                # 清理临时文件和目录
                try:
                    if os.path.exists(temp_file_path):
                        os.unlink(temp_file_path)
                    os.rmdir(temp_dir)
                except Exception:
                    pass  # 忽略清理错误

        except Exception as e:
            logger.error(f"Failed to download {artifact.file_path} to memory: {e}")
            return None

    def _upload_worker(self) -> None:
        """上传工作线程"""
        logger.info("Memory upload worker started")

        # 记录保存计数器和状态报告
        save_counter = 0
        status_counter = 0

        while not self.stop_event.is_set():
            try:
                # 定期报告状态（每30秒）
                status_counter += 1
                if status_counter % 300 == 0:  # 300 * 0.1s = 30s
                    logger.info(f"Upload worker status - Memory usage: {self.current_memory_usage}/{self.max_memory_usage} bytes, "
                               f"Queue size: {self.upload_queue.qsize()}, Uploaded: {self.stats['uploaded']}, "
                               f"Failed: {self.stats['upload_failed']}")

                # 从队列获取任务
                task = self.upload_queue.get(timeout=1.0)

                # 检查是否为结束标记
                if task is None:
                    logger.debug("Upload worker received shutdown signal")
                    break

                try:
                    if task.download_success and task.file_data:
                        # 检查是否为POM文件
                        is_pom_file = task.artifact.file_path.endswith('.pom') or task.artifact.packaging == 'pom'
                        if is_pom_file:
                            with self.pom_lock:
                                self.pom_stats['upload_attempted'] += 1
                            logger.info(f"[POM DEBUG] 🔄 STARTING POM UPLOAD: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version}")

                        # 创建临时目录和文件用于上传
                        temp_dir = tempfile.mkdtemp()
                        temp_file_path = os.path.join(temp_dir, f"upload_{hash(task.artifact.file_path)}.tmp")

                        try:
                            # 写入临时文件
                            with open(temp_file_path, 'wb') as temp_file:
                                temp_file.write(task.file_data)
                                temp_file.flush()

                            # 上传文件
                            maven_path = self._convert_to_maven_path(task.artifact)
                            logger.debug(f"[POM DEBUG] Uploading to Nexus path: {maven_path}")
                            result = self.nexus_uploader.upload_file(
                                Path(temp_file_path), maven_path
                            )

                            if result.get('success'):
                                task.upload_success = True
                                self.stats['uploaded'] += 1

                                # POM文件上传成功统计
                                if is_pom_file:
                                    with self.pom_lock:
                                        self.pom_stats['upload_success'] += 1
                                    logger.info(f"[POM DEBUG] ✅ POM UPLOAD SUCCESS: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version}")
                                    logger.info(f"[POM DEBUG]   Maven path: {maven_path}")
                                    logger.info(f"[POM DEBUG]   File size: {len(task.file_data)} bytes")
                                elif task.artifact.file_path.endswith('.pom'):
                                    with self.pom_lock:
                                        self.pom_stats['upload_success'] += 1
                                    logger.info(f"[POM DEBUG] ✅ POM UPLOAD SUCCESS: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version}")

                                # 记录已上传的依赖信息
                                repository_name = task.artifact.repository or "Unknown"
                                file_name = task.artifact.file_path.split('/')[-1] if task.artifact.file_path else "Unknown"
                                dependency_info = {
                                    'group_id': task.artifact.group_id,
                                    'artifact_id': task.artifact.artifact_id,
                                    'version': task.artifact.version,
                                    'packaging': task.artifact.packaging,
                                    'repository': repository_name,
                                    'filename': file_name,
                                    'upload_time': time.time()
                                }
                                self.uploaded_dependencies.append(dependency_info)

                                # 记录已上传的文件 - 使用Maven坐标哈希而不是文件内容哈希
                                identifier = f"{task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version}:{task.artifact.packaging}"
                                maven_hash = hashlib.md5(identifier.encode()).hexdigest()
                                self.uploaded_hashes.add(maven_hash)

                                # 清晰显示上传成功的依赖
                                logger.info(f"[OK] UPLOADED DEPENDENCY: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version} ({task.artifact.packaging})")
                                logger.info(f"   Repository: {repository_name}")
                                logger.info(f"   Filename: {file_name}")

                                # 定期保存记录（每10个上传保存一次）
                                save_counter += 1
                                if save_counter % 10 == 0:
                                    self._save_migration_records()
                            else:
                                task.error_message = result.get('error', 'Upload failed')
                                self.stats['upload_failed'] += 1
                                self.failed_tasks.append(task)

                                # 记录上传失败到日志文件
                                self._log_failed_upload(task.artifact, maven_path, task.error_message)

                                # POM文件上传失败统计
                                if is_pom_file:
                                    with self.pom_lock:
                                        self.pom_stats['upload_failed'] += 1
                                    logger.error(f"[POM DEBUG] ❌ POM UPLOAD FAILED: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version}")
                                    logger.error(f"[POM DEBUG]   Error: {task.error_message}")
                                    logger.error(f"[POM DEBUG]   Maven path: {maven_path}")

                        finally:
                            # 清理临时文件和目录
                            try:
                                if os.path.exists(temp_file_path):
                                    os.unlink(temp_file_path)
                                os.rmdir(temp_dir)
                            except Exception:
                                pass  # 忽略清理错误

                except Exception as e:
                    task.error_message = str(e)
                    self.stats['upload_failed'] += 1
                    self.failed_tasks.append(task)

                    # 记录上传失败到日志文件
                    maven_path = self._convert_to_maven_path(task.artifact)
                    self._log_failed_upload(task.artifact, maven_path, task.error_message)

                    # POM文件异常失败统计
                    is_pom_file = task.artifact.file_path.endswith('.pom') or task.artifact.packaging == 'pom'
                    if is_pom_file:
                        with self.pom_lock:
                            self.pom_stats['upload_failed'] += 1
                        logger.error(f"[POM DEBUG] ❌ POM UPLOAD EXCEPTION: {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version} - {e}")
                    logger.error(f"Failed to upload {task.artifact.file_path}: {e}")

                finally:
                    # 释放内存（重要：确保总是释放内存）
                    if task.file_data:
                        file_size = len(task.file_data)
                        with self.memory_lock:
                            self.current_memory_usage -= file_size
                        logger.debug(f"Released {file_size} bytes from memory, current usage: {self.current_memory_usage}")
                        task.file_data = None

                    # 标记任务完成
                    try:
                        self.upload_queue.task_done()
                    except Exception as task_done_error:
                        logger.error(f"Failed to mark task as done: {task_done_error}")

            except Empty:
                # 队列为空，继续等待
                continue
            except Exception as e:
                logger.error(f"Upload worker error: {e}")
                # 确保在异常情况下也等待一小段时间，避免CPU占用过高
                time.sleep(0.1)

        logger.info("Memory upload worker stopped - Final memory usage: {self.current_memory_usage} bytes")

    def _convert_to_maven_path(self, artifact: MavenArtifact) -> str:
        """转换为 Maven 路径格式"""
        parts = artifact.file_path.split('/')
        if len(parts) >= 4:
            group_id = '.'.join(parts[:-3])
            artifact_id = parts[-3]
            version = parts[-2]
            filename = parts[-1]

            return f"{group_id.replace('.', '/')}/{artifact_id}/{version}/{filename}"

        return artifact.file_path

    def _generate_final_stats(self) -> None:
        """生成最终统计信息"""
        logger.info("=" * 60)
        logger.info("MEMORY PIPELINE MIGRATION SUMMARY")
        logger.info("=" * 60)
        logger.info(f"[OK] Total artifacts processed: {self.stats['total_artifacts']}")
        logger.info(f"⬇️  Downloaded: {self.stats['downloaded']}")
        logger.info(f"⬆️  Uploaded: {self.stats['uploaded']}")
        logger.info(f"⏭️  Skipped (already uploaded): {self.stats['skipped_existing']}")
        logger.info(f"[ERROR] Download failed: {self.stats['download_failed']}")
        logger.info(f"[ERROR] Upload failed: {self.stats['upload_failed']}")
        logger.info("=" * 60)

        # POM 文件统计
        pom_uploaded = len([dep for dep in self.uploaded_dependencies if dep['packaging'] == 'pom'])
        logger.info(f"POM files uploaded: {pom_uploaded}")

        if self.failed_tasks:
            # 专门统计 POM 文件失败
            pom_failed = [task for task in self.failed_tasks if task.artifact.packaging == 'pom']
            if pom_failed:
                logger.warning(f"POM files failed: {len(pom_failed)}")
                for task in pom_failed[:3]:  # 显示前3个POM错误
                    logger.warning(f"  POM - {task.artifact.group_id}:{task.artifact.artifact_id}:{task.artifact.version} - {task.error_message}")

        processed = self.stats['uploaded'] + self.stats['upload_failed']
        success_rate = (self.stats['uploaded'] / processed * 100) if processed > 0 else 0
        logger.info(f"Upload success rate: {success_rate:.1f}%")

        # 检查是否有缺失的 POM 文件
        jar_uploaded = len([dep for dep in self.uploaded_dependencies if dep['packaging'] == 'jar'])
        missing_poms = []
        for dep in self.uploaded_dependencies:
            if dep['packaging'] == 'jar':
                # 检查是否有对应的 POM 文件
                matching_pom = any(p['group_id'] == dep['group_id'] and
                                  p['artifact_id'] == dep['artifact_id'] and
                                  p['version'] == dep['version'] and
                                  p['packaging'] == 'pom'
                                  for p in self.uploaded_dependencies)
                if not matching_pom:
                    missing_poms.append(f"{dep['group_id']}:{dep['artifact_id']}:{dep['version']}")

        if missing_poms:
            logger.warning(f"⚠️  Found {len(missing_poms)} JAR files without corresponding POM files:")
            for missing in missing_poms[:5]:  # 显示前5个缺失的POM
                logger.warning(f"  - {missing}")
            if len(missing_poms) > 5:
                logger.warning(f"  ... and {len(missing_poms) - 5} more")

            # 更新POM统计中的缺失列表
            with self.pom_lock:
                self.pom_stats['missing_in_nexus'] = missing_poms

    def _display_pom_detailed_report(self) -> None:
        """显示POM文件详细统计报告"""
        logger.info("")
        logger.info("📋 POM FILE DETAILED REPORT")
        logger.info("=" * 80)

        with self.pom_lock:
            stats = self.pom_stats.copy()

        logger.info(f"[DISCOVERY] POM files found in CODING: {stats['discovered_in_coding']}")
        logger.info(f"[SKIPPED] POM files already uploaded: {stats['skipped_already_uploaded']}")
        logger.info(f"[DOWNLOAD] POM files download attempted: {stats['download_attempted']}")
        logger.info(f"[DOWNLOAD] POM files download success: {stats['download_success']}")
        logger.info(f"[DOWNLOAD] POM files download failed: {stats['download_failed']}")
        logger.info(f"[UPLOAD] POM files upload attempted: {stats['upload_attempted']}")
        logger.info(f"[UPLOAD] POM files upload success: {stats['upload_success']}")
        logger.info(f"[UPLOAD] POM files upload failed: {stats['upload_failed']}")

        # 计算成功率
        if stats['download_attempted'] > 0:
            download_success_rate = (stats['download_success'] / stats['download_attempted']) * 100
            logger.info(f"[RATE] POM download success rate: {download_success_rate:.1f}%")

        if stats['upload_attempted'] > 0:
            upload_success_rate = (stats['upload_success'] / stats['upload_attempted']) * 100
            logger.info(f"[RATE] POM upload success rate: {upload_success_rate:.1f}%")

        # 分析问题
        logger.info("")
        logger.info("🔍 POM FILE ANALYSIS:")

        if stats['discovered_in_coding'] == 0:
            logger.warning("⚠️  No POM files discovered in CODING repositories")
            logger.warning("   This could indicate:")
            logger.warning("   - No Maven projects with POM files in the repositories")
            logger.warning("   - POM files are filtered out by maven_filter configuration")
            logger.warning("   - API access issues preventing POM file discovery")
        elif stats['download_attempted'] < stats['discovered_in_coding']:
            skipped_count = stats['discovered_in_coding'] - stats['download_attempted'] - stats['skipped_already_uploaded']
            if skipped_count > 0:
                logger.warning(f"⚠️  {skipped_count} POM files discovered but not attempted for download")
                logger.warning("   This could indicate:")
                logger.warning("   - Files were incorrectly marked as already uploaded")
                logger.warning("   - Memory or processing issues prevented download attempts")

        if stats['download_failed'] > 0:
            failure_rate = (stats['download_failed'] / stats['download_attempted']) * 100 if stats['download_attempted'] > 0 else 0
            logger.warning(f"⚠️  {stats['download_failed']} POM files failed to download ({failure_rate:.1f}% failure rate)")
            logger.warning("   Possible causes:")
            logger.warning("   - Authentication issues with CODING Maven repositories")
            logger.warning("   - Network connectivity problems")
            logger.warning("   - POM files were deleted or moved in CODING")
            logger.warning("   - Temporary API errors or rate limiting")

        if stats['upload_failed'] > 0:
            failure_rate = (stats['upload_failed'] / stats['upload_attempted']) * 100 if stats['upload_attempted'] > 0 else 0
            logger.warning(f"⚠️  {stats['upload_failed']} POM files failed to upload ({failure_rate:.1f}% failure rate)")
            logger.warning("   Possible causes:")
            logger.warning("   - Nexus repository connection issues")
            logger.warning("   - Insufficient permissions in Nexus")
            logger.warning("   - Nexus repository configuration problems")
            logger.warning("   - Network issues between migration tool and Nexus")

        # 缺失的POM文件分析
        if stats['missing_in_nexus']:
            logger.warning(f"⚠️  {len(stats['missing_in_nexus'])} JAR files in Nexus are missing corresponding POM files:")
            for missing in stats['missing_in_nexus'][:10]:  # 显示前10个
                logger.warning(f"  - {missing}")
            if len(stats['missing_in_nexus']) > 10:
                logger.warning(f"  ... and {len(stats['missing_in_nexus']) - 10} more")

            logger.warning("")
            logger.warning("   This indicates that POM files:")
            logger.warning("   - May not exist in CODING (check discovery count above)")
            logger.warning("   - Failed to download from CODING")
            logger.warning("   - Failed to upload to Nexus")
            logger.warning("   - Were processed but had errors during migration")

        logger.info("=" * 80)
        logger.info("")

        # 建议的调试步骤
        if stats['discovered_in_coding'] > 0 and (stats['download_failed'] > 0 or stats['upload_failed'] > 0 or len(stats['missing_in_nexus']) > 0):
            logger.info("🔧 SUGGESTED DEBUGGING STEPS:")
            logger.info("1. Check the detailed [POM DEBUG] logs above for specific error messages")
            logger.info("2. Review failed dependency logs:")
            logger.info(f"   - CODING download failures: {self.failed_download_log}")
            logger.info(f"   - Nexus upload failures: {self.failed_upload_log}")
            logger.info("3. Verify CODING Maven repository authentication in config.yaml")
            logger.info("4. Test manual access to CODING Maven repository URLs")
            logger.info("5. Check Nexus repository permissions and configuration")
            logger.info("6. Verify network connectivity to both CODING and Nexus")
            logger.info("7. Consider running with logging level set to DEBUG for more details")
            logger.info("")

    def migrate_components(self, components: List[dict]) -> Dict[str, Any]:
        """
        迁移指定的组件

        Args:
            components: 组件列表，每个组件包含 group_id, artifact_id, version

        Returns:
            迁移结果统计
        """
        logger.info(f"Starting memory pipeline migration for {len(components)} components")

        # 初始化统计信息
        stats = {
            'total_artifacts': 0,
            'downloaded': 0,
            'uploaded': 0,
            'download_failed': 0,
            'upload_failed': 0,
            'skipped_existing': 0
        }

        try:
            # 为组件迁移创建专门的记录文件
            import time
            timestamp = int(time.time())
            self.record_file = self.records_dir / f"components_migration_{timestamp}.json"
            self._load_migration_records()

            # 获取所有项目以用于查找组件
            all_projects = self.coding_client.get_all_projects()
            if not all_projects:
                logger.error("[ERROR] 无法获取任何项目信息")
                return stats

            # 获取每个项目的仓库信息
            all_artifacts = []

            for component in components:
                group_id = component['group_id']
                artifact_id = component['artifact_id']
                version = component['version']
                package_name = f"{group_id}:{artifact_id}"

                logger.info(f"[SEARCH] 查找组件: {package_name}:{version}")

                component_found = False

                # 在所有项目中查找这个组件
                for project in all_projects:
                    logger.debug(f"[SEARCH] 在项目 {project.name} (ID: {project.id}) 中查找...")

                    # 获取项目的仓库信息
                    repositories = []
                    try:
                        repos = self.coding_client.get_artifact_repositories(project.id)
                        for repo in repos:
                            if repo.get('Type') == 3:  # Maven 类型
                                repositories.append(repo.get('Name'))
                        logger.debug(f"[SEARCH] 项目 {project.name} 找到 Maven 仓库: {repositories}")
                    except Exception as e:
                        logger.debug(f"[SEARCH] 获取项目 {project.name} 仓库信息失败: {e}")
                        continue

                    # 在每个仓库中查找组件
                    for repository_name in repositories:
                        try:
                            logger.debug(f"[SEARCH] 在仓库 {repository_name} 中查找 {package_name}:{version}")

                            # 调用 get_maven_version_files 获取组件的文件列表
                            artifacts = self.coding_client.get_maven_version_files(
                                project.id, project.name, repository_name, package_name, version
                            )
                            logger.info(f"[SEARCH] 仓库 {repository_name} 返回了 {len(artifacts) if artifacts else 0} 个制品")

                            if artifacts:
                                logger.info(f"[SUCCESS] 在项目 {project.name} 的仓库 {repository_name} 中找到 {len(artifacts)} 个文件")
                                logger.info(f"[INFO] 文件列表: {[a.download_url.split('/')[-1] for a in artifacts[:5]]}")

                                # 添加项目名称到制品信息中
                                for artifact in artifacts:
                                    # 为制品对象添加项目信息
                                    artifact.project_name = project.name
                                    artifact.project_id = project.id
                                    # 如果仓库信息为空，则设置
                                    if not artifact.repository:
                                        artifact.repository = repository_name

                                all_artifacts.extend(artifacts)
                                component_found = True
                                logger.info(f"[SUCCESS] 组件 {package_name}:{version} 查找成功，共找到 {len(all_artifacts)} 个文件")
                                logger.info(f"[DEBUG] 设置 component_found = True，准备跳出仓库循环")

                                # 组件在一个项目中找到后，就不在其他项目中继续查找
                                break

                        except Exception as e:
                            logger.debug(f"[SEARCH] 在仓库 {repository_name} 中查找失败: {e}")
                            continue

                    logger.info(f"[DEBUG] 完成项目 {project.name} 的所有仓库查找，component_found = {component_found}")
                    if component_found:
                        logger.info(f"[DEBUG] component_found = True，准备跳出项目循环")
                        break

                if not component_found:
                    logger.warning(f"[NOT FOUND] 组件 {package_name}:{version} 在所有项目中都未找到")

            stats['total_artifacts'] = len(all_artifacts)

            if not all_artifacts:
                logger.warning("[WARNING] 没有找到任何组件文件")
                logger.info("[INFO] 可能的原因:")
                logger.info("  1. 组件坐标不正确")
                logger.info("  2. 版本号不匹配")
                logger.info("  3. 组件不在任何 CODING Maven 仓库中")
                logger.info("  4. 仓库访问权限问题")
                return stats

            logger.info(f"[INFO] 总共找到 {len(all_artifacts)} 个文件待迁移")
            logger.info(f"[INFO] 文件预览: {[a.file_path for a in all_artifacts[:5]]}")  # 显示前5个文件路径

            # 过滤已上传的制品
            filtered_artifacts = []
            for artifact in all_artifacts:
                existing_hash = self._check_if_already_uploaded(artifact)
                if existing_hash:
                    stats['skipped_existing'] += 1
                    logger.debug(f"Skipping already uploaded: {artifact.file_path}")
                else:
                    filtered_artifacts.append(artifact)

            logger.info(f"Found {len(all_artifacts)} total artifacts, {len(filtered_artifacts)} to migrate "
                       f"({stats['skipped_existing']} already uploaded)")

            if not filtered_artifacts:
                logger.info("All artifacts have already been migrated")
                return stats

            # 执行迁移逻辑（复用现有的流水线逻辑）
            # 重置队列和统计
            self.upload_queue = Queue(maxsize=50)
            self.completed_tasks = []
            self.failed_tasks = []
            self.stats = stats.copy()
            self.stop_event.clear()

            # 启动下载和上传线程池
            with ThreadPoolExecutor(max_workers=self.download_workers + self.upload_workers) as executor:
                # 启动上传工作线程
                upload_futures = []
                for i in range(self.upload_workers):
                    future = executor.submit(self._upload_worker)
                    upload_futures.append(future)

                # 启动下载工作线程
                download_futures = []
                for artifact in filtered_artifacts:
                    if self.stop_event.is_set():
                        break
                    future = executor.submit(self._download_artifact_simple, artifact)
                    download_futures.append(future)

                # 等待所有下载任务完成
                for future in as_completed(download_futures):
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Download task failed: {e}")

                # 添加结束标记到上传队列
                for _ in range(self.upload_workers):
                    self.upload_queue.put(None)

                # 等待所有上传任务完成
                for future in as_completed(upload_futures):
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Upload worker failed: {e}")

            # 保存迁移记录
            self._save_migration_records()

            # 记录最终统计
            final_stats = self.stats.copy()
            # 确保 total_artifacts 反映实际找到的制品数
            final_stats['total_artifacts'] = len(all_artifacts)
            logger.info(f"Component migration completed:")
            logger.info(f"  Total artifacts: {final_stats['total_artifacts']}")
            logger.info(f"  Downloaded: {final_stats['downloaded']}")
            logger.info(f"  Uploaded: {final_stats['uploaded']}")
            logger.info(f"  Skipped existing: {final_stats['skipped_existing']}")
            logger.info(f"  Download failed: {final_stats['download_failed']}")
            logger.info(f"  Upload failed: {final_stats['upload_failed']}")

            return final_stats

        except Exception as e:
            logger.error(f"Component migration failed: {e}")
            stats['error'] = str(e)
            return stats